version: '{branch}-{build}'
# we can't use shallow_clone to fetch a zip archive instead of git clone
# becuse we need the git clone to run in order to have a git repo that coveralls can look at.
clone_depth: 10
build: off
cache:
  - '%LOCALAPPDATA%\pip\Cache'
environment:
  COVERALLS_REPO_TOKEN:
    secure: S3EBGxvldWiG3LObRlB3lqqg4pABw3OzBtwu/4OiJOYRwls5DokJjXTT8N0wbCmW
  # SAUCE_USERNAME: nbext_configurator
  # SAUCE_ACCESS_KEY:
  #   secure: B5VK1YhWE9WmgkdCa3cLBPXIM0u3qBnV1jg8LgAI0tQYmQgl+URn5Y3LTHUaD9GX
  matrix:


init:
  - ps: echo $env:TOXENV
  - ps: ls C:\Python*
install:
  # Prepend newly installed Python to the PATH of this build (this cannot be
  # done from inside a powershell script as it would require us to restart the
  # parent CMD process).
  - "SET PATH=%PYTHON_HOME%;%PYTHON_HOME%\\Scripts;%PATH%"
  # Check that we have the expected version and architecture for Python
  - "python --version"
  - "python -c \"import struct; print(struct.calcsize('P') * 8)\""
  # Upgrade to the latest version of pip to avoid it displaying warnings
  # about it being out of date.
  - 'python -m pip install --disable-pip-version-check --user --upgrade pip'
  # install tox
  - pip install tox
  # install of the actual project is handled by tox in tests
test_script:
  # run tox tests
  - '%PYTHON_HOME%\Scripts\tox -e %TOXENV%'

after_test:
  - cmd: '%PYTHON_HOME%\Scripts\tox -e codecov || (echo "codecov failed :(" && cmd /c "exit /b 0")'
on_failure:
  - ps: $($env:COVERALLS_REPO_TOKEN = '')
  - ps: $($env:SAUCE_ACCESS_KEY = '')
  - ps: dir "env:"
  - ps: get-content .tox\*\log\*
artifacts:
  - path: .coverage
  - path: dist\*

### To enable remote debugging uncomment this (also, see: http://www.appveyor.com/docs/how-to/rdp-to-build-worker):
# on_finish:
#   - ps: $blockRdp = $true; iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))
